version: "3"
services:
  spring-boot-ecommerce:
    image: spring-boot-ecommerce:0.0.1
    build: .
    ports:
      - "9090:9090"
    networks:
      - mysql-network
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
      - MYSQL_PASSWORD=root
    volumes:
      # this is a bind-mount volume (physical directory on host machine)
      - D:\docker-volumes\ecommerce:/var/lib/mysql

networks:
  mysql-network:
    external: false
    name: mysql-network
