server:
  port: 9090
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        jdbc:
          time_zone: Africa/Cairo
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace