version: "3"
services:
  spring-boot-ecommerce:
    image: spring-boot-ecommerce:latest
    build: .
    ports:
      - "9090:9090"
    networks:
      - mongo-db-network
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    networks:
      - mongo-db-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - D:\docker-volumes\mongo-ecommerce:/data/db

networks:
  mongo-db-network:
    external: true
    name: mongo-db-network